version: "3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ".:/next-test"
    command: sh -c 'npm run dev'
    tty: true
    stdin_open: true
    environment:
      - "NEWS_API_KEY=8fa532d03cc140628bf2e00ebf1b387f"
